CC = g++
CFLAGS = -g -Wall -Wpedantic -Werror -I.

# add to this variable path to directory with sources
SRCDIR=

# add to this variable project name
PROJ_NAME=

SOURCES := $(wildcard $(SRCDIR)/*.cpp)
OBJECTS := $(SOURCES:$(SRCDIR)/%.cpp=%.o)

all :$(PROJ_NAME) $(CLEAN_OBJECTS)

$(PROJ_NAME) : $(OBJECTS)
        $(CC) $(CFLAGS) $(LFLAGS) $^ -o $@
        rm -rf *.o

$(OBJECTS) : %.o : $(SRCDIR)/%.cpp
        $(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean
clean :
        rm -rf $(PROJ_NAME)
